---
projects:
  -
    uid: ov
    dir: /home/sieg/Projects/nup/overlord
    run: bin/ov
    build: make
    test: make tests && bin/run_tests
  -
    uid: sig
    dir: /home/sieg/Projects/gbi/cust_signet
    run: npm run start
    build: npm run build
...