sudo: require
os: linux
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-7 binutils-2.26 --allow-unauthenticated
  # Set compiler env vars to new gcc version
  - export CC="gcc-7"
  - export CXX="g++-7"
  - export PATH=/usr/lib/binutils-2.26/bin:${PATH}
  # Check versions of gcc, g++ and cmake
  - gcc-7 -v && g++-7 -v && ld -v

script:
  # Export CC and CXX to tell cmake which compiler to use
  - export CC="gcc-7"
  - export CXX="g++-7"
  - export PATH=/usr/lib/binutils-2.26/bin:${PATH}
  # Check versions of gcc, g++ and cmake
  - gcc-7 -v && g++-7 -v && ld -v
  # Make app and run tests
  - make
  - make tests
  - bin/run_tests

after_success: 
  - bash <(curl -s https://codecov.io/bash)