dist: trusty
sudo: require
language: c++

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

# before_install:
#   - |
#     if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
#       sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y \
#       && sudo apt-get update -qq \
#       && if [ "$CXX" == "g++" ]; then
#         sudo apt-get install -qq g++-5 && export CXX="g++-5" CC="gcc-5"
#       fi
#     fi

script:
  # Link gcc-6 and g++-6 to their standard commands
  - ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - ln -s /usr/bin/g++-6 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Make app and run tests
  - make
  - make tests
  - bin/run_tests

after_success: 
  - bash <(curl -s https://codecov.io/bash)