language: c++

os:
  - linux

compiler:
  - gcc

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y \
      && sudo apt-get update -qq \
      && if [ "$CXX" == "g++" ]; then
        sudo apt-get install -qq g++-4.7 && export CXX="g++-4.7" CC="gcc-4.7"
      fi
    fi

script:
  - make
  - make tests
  - bin/run_tests
  - codecov

after_success: 
  - bash <(curl -s https://codecov.io/bash)