language: c++
os:
  - linux
compiler:
  - gcc
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt install gcc
      sudo apt install g++
    fi
script:
  - make
  - make tester
  - bin/tester